# Generated by Django 5.2.1 on 2025-05-16 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Nombre completo tal como aparecerá en el CV', max_length=200)),
                ('titulo_cv', models.CharField(help_text='Ej: Desarrollador Full Stack, Ingeniero de Software', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.TextField(help_text='Un breve resumen de tu perfil y objetivos profesionales.')),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profesional', to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Particularmente útil para perfiles junior o si estás cambiando de carrera.')),
                ('portfolio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivo_profesional', to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='InteresHobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion_breve', models.CharField(blank=True, help_text='Si es relevante o muestra habilidades transferibles', max_length=255, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intereses_hobbies', to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_idioma', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('NATIVO', 'Nativo'), ('A1', 'A1 - Principiante'), ('A2', 'A2 - Elemental'), ('B1', 'B1 - Intermedio bajo'), ('B2', 'B2 - Intermedio'), ('C1', 'C1 - Intermedio alto'), ('C2', 'C2 - Avanzado')], max_length=10)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_habilidad', models.CharField(max_length=100)),
                ('tipo_habilidad', models.CharField(choices=[('LENGUAJE', 'Lenguaje de Programación'), ('FRAMEWORK', 'Framework/Librería'), ('BASE_DATOS', 'Base de Datos'), ('HERRAMIENTA', 'Herramienta/Tecnología'), ('METODOLOGIA', 'Metodología de Trabajo'), ('BLANDA', 'Habilidad Blanda')], max_length=20)),
                ('nivel', models.CharField(blank=True, help_text='Ej: Básico, Intermedio, Avanzado, Experto', max_length=50, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_obtenido', models.CharField(max_length=255)),
                ('institucion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar en blanco si está en curso', null=True)),
                ('menciones', models.TextField(blank=True, help_text='Menciones honoríficas o logros académicos', null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formaciones_academicas', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['-fecha_fin', '-orden'],
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('ubicacion_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar en blanco si es el trabajo actual', null=True)),
                ('descripcion', models.TextField(help_text='Responsabilidades y logros clave. Usa viñetas si es posible.')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Para ordenar las experiencias (más reciente primero)')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_laborales', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['-fecha_inicio', '-orden'],
            },
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(help_text='Correo electrónico profesional', max_length=255)),
                ('ubicacion', models.CharField(help_text='Ciudad y país de residencia', max_length=100)),
                ('linkedin_url', models.URLField(blank=True, help_text='Enlace a tu perfil de LinkedIn', null=True)),
                ('github_url', models.URLField(blank=True, help_text='Enlace a tu perfil de GitHub', null=True)),
                ('website_url', models.URLField(blank=True, help_text='Enlace a tu portfolio personal o blog', null=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_personales', to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='CursoCertificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=255)),
                ('institucion_emisora', models.CharField(max_length=255)),
                ('fecha_obtencion', models.DateField(blank=True, null=True)),
                ('certificado_url', models.URLField(blank=True, help_text='Enlace al certificado (PDF, imagen)', null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_certificaciones', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['-fecha_obtencion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=200)),
                ('descripcion_proyecto', models.TextField()),
                ('tecnologias_utilizadas', models.CharField(help_text='Ej: Python, Django, React, PostgreSQL', max_length=300)),
                ('repositorio_url', models.URLField(blank=True, help_text='Enlace al repositorio (GitHub, GitLab)', null=True)),
                ('demo_url', models.URLField(blank=True, help_text='Enlace a la demo en vivo', null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PublicacionConferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('enlace', models.URLField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_conferencias', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['-fecha', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Voluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacion', models.CharField(max_length=200)),
                ('puesto_rol', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntariados', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['-fecha_inicio', 'orden'],
            },
        ),
    ]
